/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * resource representation of a bar series
 */
@ApiModel(description = "resource representation of a bar series")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-28T16:56:05.648-07:00")
public class BarSeries {
  @SerializedName("label")
  private String label = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("values")
  private List<Double> values = null;

  public BarSeries label(String label) {
    this.label = label;
    return this;
  }

   /**
   * label for this sebar series
   * @return label
  **/
  @ApiModelProperty(value = "label for this sebar series")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public BarSeries color(String color) {
    this.color = color;
    return this;
  }

   /**
   * target color
   * @return color
  **/
  @ApiModelProperty(value = "target color")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public BarSeries values(List<Double> values) {
    this.values = values;
    return this;
  }

  public BarSeries addValuesItem(Double valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<Double>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * target values
   * @return values
  **/
  @ApiModelProperty(value = "target values")
  public List<Double> getValues() {
    return values;
  }

  public void setValues(List<Double> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarSeries barSeries = (BarSeries) o;
    return Objects.equals(this.label, barSeries.label) &&
        Objects.equals(this.color, barSeries.color) &&
        Objects.equals(this.values, barSeries.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, color, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarSeries {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

