/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CacheApiBean;
import java.util.ArrayList;
import java.util.List;

/**
 * store resource representation
 */
@ApiModel(description = "store resource representation")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-28T16:56:05.648-07:00")
public class FeatureStoreApiBean {
  @SerializedName("type")
  private String type = null;

  @SerializedName("numberOfFeatures")
  private Integer numberOfFeatures = null;

  @SerializedName("numberOfGroups")
  private Integer numberOfGroups = null;

  @SerializedName("features")
  private List<String> features = new ArrayList<String>();

  @SerializedName("groups")
  private List<String> groups = new ArrayList<String>();

  @SerializedName("cache")
  private CacheApiBean cache = null;

  public FeatureStoreApiBean type(String type) {
    this.type = type;
    return this;
  }

   /**
   * classname of implementation
   * @return type
  **/
  @ApiModelProperty(required = true, value = "classname of implementation")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FeatureStoreApiBean numberOfFeatures(Integer numberOfFeatures) {
    this.numberOfFeatures = numberOfFeatures;
    return this;
  }

   /**
   * number of features
   * @return numberOfFeatures
  **/
  @ApiModelProperty(required = true, value = "number of features")
  public Integer getNumberOfFeatures() {
    return numberOfFeatures;
  }

  public void setNumberOfFeatures(Integer numberOfFeatures) {
    this.numberOfFeatures = numberOfFeatures;
  }

  public FeatureStoreApiBean numberOfGroups(Integer numberOfGroups) {
    this.numberOfGroups = numberOfGroups;
    return this;
  }

   /**
   * number of group
   * @return numberOfGroups
  **/
  @ApiModelProperty(required = true, value = "number of group")
  public Integer getNumberOfGroups() {
    return numberOfGroups;
  }

  public void setNumberOfGroups(Integer numberOfGroups) {
    this.numberOfGroups = numberOfGroups;
  }

  public FeatureStoreApiBean features(List<String> features) {
    this.features = features;
    return this;
  }

  public FeatureStoreApiBean addFeaturesItem(String featuresItem) {
    this.features.add(featuresItem);
    return this;
  }

   /**
   * list of features
   * @return features
  **/
  @ApiModelProperty(required = true, value = "list of features")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }

  public FeatureStoreApiBean groups(List<String> groups) {
    this.groups = groups;
    return this;
  }

  public FeatureStoreApiBean addGroupsItem(String groupsItem) {
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * list of group
   * @return groups
  **/
  @ApiModelProperty(required = true, value = "list of group")
  public List<String> getGroups() {
    return groups;
  }

  public void setGroups(List<String> groups) {
    this.groups = groups;
  }

  public FeatureStoreApiBean cache(CacheApiBean cache) {
    this.cache = cache;
    return this;
  }

   /**
   * if a cachestore is defined
   * @return cache
  **/
  @ApiModelProperty(required = true, value = "if a cachestore is defined")
  public CacheApiBean getCache() {
    return cache;
  }

  public void setCache(CacheApiBean cache) {
    this.cache = cache;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureStoreApiBean featureStoreApiBean = (FeatureStoreApiBean) o;
    return Objects.equals(this.type, featureStoreApiBean.type) &&
        Objects.equals(this.numberOfFeatures, featureStoreApiBean.numberOfFeatures) &&
        Objects.equals(this.numberOfGroups, featureStoreApiBean.numberOfGroups) &&
        Objects.equals(this.features, featureStoreApiBean.features) &&
        Objects.equals(this.groups, featureStoreApiBean.groups) &&
        Objects.equals(this.cache, featureStoreApiBean.cache);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, numberOfFeatures, numberOfGroups, features, groups, cache);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureStoreApiBean {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    numberOfFeatures: ").append(toIndentedString(numberOfFeatures)).append("\n");
    sb.append("    numberOfGroups: ").append(toIndentedString(numberOfGroups)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

