/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Description of a group
 */
@ApiModel(description = "Description of a group")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-28T16:56:05.648-07:00")
public class GroupDescApiBean {
  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("features")
  private List<String> features = new ArrayList<String>();

  public GroupDescApiBean groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * name of current group
   * @return groupName
  **/
  @ApiModelProperty(required = true, value = "name of current group")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public GroupDescApiBean features(List<String> features) {
    this.features = features;
    return this;
  }

  public GroupDescApiBean addFeaturesItem(String featuresItem) {
    this.features.add(featuresItem);
    return this;
  }

   /**
   * name of current group
   * @return features
  **/
  @ApiModelProperty(required = true, value = "name of current group")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupDescApiBean groupDescApiBean = (GroupDescApiBean) o;
    return Objects.equals(this.groupName, groupDescApiBean.groupName) &&
        Objects.equals(this.features, groupDescApiBean.features);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, features);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupDescApiBean {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

