/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.FeatureApiBean;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Ff4jstorefeaturesuidApi
 */
@Ignore
public class Ff4jstorefeaturesuidApiTest {

    private final Ff4jstorefeaturesuidApi api = new Ff4jstorefeaturesuidApi();

    
    /**
     * Delete a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFeatureTest() throws ApiException {
        String uid = null;
        api.deleteFeature(uid);

        // TODO: test validations
    }
    
    /**
     * Define the group of the feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationAddGroupTest() throws ApiException {
        String uid = null;
        String groupName = null;
        api.operationAddGroup(uid, groupName);

        // TODO: test validations
    }
    
    /**
     * Disable a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationDisableTest() throws ApiException {
        String uid = null;
        api.operationDisable(uid);

        // TODO: test validations
    }
    
    /**
     * Enable a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationEnableTest() throws ApiException {
        String uid = null;
        api.operationEnable(uid);

        // TODO: test validations
    }
    
    /**
     * Grant a permission on a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationGrantRoleTest() throws ApiException {
        String uid = null;
        String role = null;
        api.operationGrantRole(uid, role);

        // TODO: test validations
    }
    
    /**
     * Remove the group of the feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationRemoveGroupTest() throws ApiException {
        String uid = null;
        String groupName = null;
        api.operationRemoveGroup(uid, groupName);

        // TODO: test validations
    }
    
    /**
     * Remove a permission on a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationRemoveRoleTest() throws ApiException {
        String uid = null;
        String role = null;
        api.operationRemoveRole(uid, role);

        // TODO: test validations
    }
    
    /**
     * Read information about a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readTest() throws ApiException {
        String uid = null;
        api.read(uid);

        // TODO: test validations
    }
    
    /**
     * Create of update a feature
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void upsertFeatureTest() throws ApiException {
        String uid = null;
        FeatureApiBean body = null;
        api.upsertFeature(uid, body);

        // TODO: test validations
    }
    
}
