/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Authorization;
import io.swagger.client.model.Ff4jStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Ff4jApi
 */
@Ignore
public class Ff4jApiTest {

    private final Ff4jApi api = new Ff4jApi();

    
    /**
     * &lt;b&gt;Simple check&lt;/b&gt; feature toggle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkTest() throws ApiException {
        String uid = null;
        api.check(uid);

        // TODO: test validations
    }
    
    /**
     * &lt;b&gt;Advanced check&lt;/b&gt; feature toggle (parameterized)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkPOSTTest() throws ApiException {
        String uid = null;
        api.checkPOST(uid);

        // TODO: test validations
    }
    
    /**
     * Display &lt;b&gt;Security&lt;/b&gt; informations (permissions manager)
     *
     * Security is implemented through dedicated &lt;b&gt;AuthorizationsManager&lt;/b&gt; but it&#39;s not mandatory
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSecurityStatusTest() throws ApiException {
        Authorization response = api.getSecurityStatus();

        // TODO: test validations
    }
    
    /**
     * Display &lt;b&gt;ff4j&lt;/b&gt; status overview
     *
     * Display informations related to &lt;b&gt;Monitoring&lt;/b&gt;, &lt;b&gt;Security&lt;/b&gt;, &lt;b&gt;Cache&lt;/b&gt; and &lt;b&gt;Store&lt;/b&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws ApiException {
        Ff4jStatus response = api.getStatus();

        // TODO: test validations
    }
    
}
