/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api
 *
 * OpenAPI spec version: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CacheApiBean;
import io.swagger.client.model.FpropertyStoreApiBean;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Ff4jpropertyStoreApi
 */
@Ignore
public class Ff4jpropertyStoreApiTest {

    private final Ff4jpropertyStoreApi api = new Ff4jpropertyStoreApi();

    
    /**
     * Clear Cache
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearTest() throws ApiException {
        api.clear();

        // TODO: test validations
    }
    
    /**
     * Delete all &lt;b&gt;Properties&lt;/b&gt; in store
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearPropertiesTest() throws ApiException {
        FpropertyStoreApiBean response = api.clearProperties();

        // TODO: test validations
    }
    
    /**
     * Display information regarding to &lt;b&gt;Properties&lt;/b&gt;
     *
     * other sub resources to be displayed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        api.get();

        // TODO: test validations
    }
    
    /**
     * Display information related to &lt;b&gt;Cache&lt;/b&gt;
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws ApiException {
        CacheApiBean response = api.getStatus();

        // TODO: test validations
    }
    
    /**
     * Display information regarding &lt;b&gt;Properties&lt;/b&gt;
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readPropertiesTest() throws ApiException {
        api.readProperties();

        // TODO: test validations
    }
    
}
